src/object_identitifer.rs

Document ObjectIdentifier

---

src/bit_string.rs

Document BitString

---

src/parser.rs

Document parse() and ParseError

---

src/parser.rs

Document read_element()

---

src/parser.rs

Document PrintableString

---

src/lib.rs
src/parser.rs

Document UtcTime

---

src/parser.rs

Document Choice

---

src/parser.rs

Document Sequence

---

src/parser.rs

Document Implicit and Explicit

---

README.rst
src/lib.rs
src/parser.rs

Also implement parsing for u64.
Fixes #55

Write module level documentation.

---

src/lib.rs
src/types.rs

Switch to using min-const-generics

---

fuzz/fuzz_targets/fuzz_asn1_parse.rs
src/lib.rs
src/parser.rs
src/types.rs
src/writer.rs

Needing review: If the `tlv < tlv` comparison correct?

Support SetOf

---

Cargo.toml
src/bit_string.rs
src/parser.rs
src/types.rs

just a non-compiling test ATM... I am hoping we can get this to work

Fixed lifetimes coming from inside a Sequence

---

fuzz/fuzz_targets/fuzz_asn1_parse.rs
src/parser.rs
src/types.rs

Still requires 0 allocations/scratch memory

Make SequenceOf and SetOf be iterators over T by pre-parsing their contents

---

asn1_derive/src/lib.rs
src/lib.rs
src/parser.rs
src/types.rs
tests/derive_test.rs

Support a default annotation for derive

---

src/lib.rs
src/object_identifier.rs
src/parser.rs

the author's signature, while unique, is confusing

identitifer -> identifier

---

asn1_derive/src/lib.rs

This should make it much cleaner to add derive support for choices

Rearrange code in the derive implementation

---

asn1_derive/src/lib.rs
src/lib.rs
tests/derive_test.rs

Added very basic support for enums in derive

---

src/object_identifier.rs
src/parser.rs
src/types.rs

Revert "Make OID storage fixed length - this will make it possible for them to be structurally equal"

---

src/types.rs

add clone trait to generalizedtime

---

.github/workflows/ci.yml

it's still finding new paths at 10 minutes

fuzz for longer on main

---

src/lib.rs
src/parser.rs
src/types.rs
src/writer.rs

I may still need to do something with the macro, although I see it carries $sign so maybe not?

support signed integers (boooooo)

---

src/object_identifier.rs
src/types.rs

Make the representation of ObjectIdentifier more private.

---

src/object_identifier.rs

Also leads to much saner code generation

Simplify how _write_base128_int works

---

asn1_derive/src/lib.rs
src/lib.rs
src/parser.rs
src/tag.rs
src/types.rs
src/writer.rs
tests/derive_test.rs

This is part N of supporting long tag forms

Create a dedicated type for Tags

---

src/object_identifier.rs

This will make it easier to use in other contexts.

Refactor _read_base128_int to not use an Iterator

---

.github/workflows/ci.yml

Compute coverage in CI

---

.github/workflows/ci.yml

Introduce a ratchet enforcing minimum coverage

---

.github/workflows/ci.yml
src/object_identifier.rs

Complete coverage for `object_identifier.rs`

---

.github/workflows/ci.yml
tests/oid_tests.rs

Previously it was only taking into account one of our test binaries, not all of them

Fix coverage generation

---

src/tag.rs

rewrite match statement to be if-chain to avoid the unreachable branch

refs #274 -- complete coverage for tag.rs

---

asn1_derive/src/lib.rs
examples/no_std.rs
fuzz/fuzz_targets/fuzz_asn1_parse.rs
src/lib.rs
src/parser.rs
src/types.rs
src/writer.rs
tests/derive_test.rs
tests/roundtrip_tests.rs

in the future these will be used to handle fallible allocations

refs #283 -- make write() functions fallible

---

asn1_derive/src/lib.rs

Don't add a lifetime in `#[derive(asn1::Asn1Write)]`

---

src/parser.rs
src/types.rs

Added testcases for time edge cases

---

src/parser.rs
src/tag.rs
src/types.rs
src/writer.rs
tests/derive_test.rs

Plus some other general purpose cleanup

Fix several clippy pedantic warnings (not on by default)

---

fuzz/fuzz_targets/fuzz_asn1_parse.rs

This makes it way easier to get coverage.

Switch the fuzzer to use an enum.

---

asn1_derive/Cargo.toml

What we require matches syn's defaults

Remove pointless params for syn

---

Cargo.toml
asn1_derive/Cargo.toml
asn1_derive/src/lib.rs
src/parser.rs
src/types.rs
src/writer.rs

Several cleanups

---

asn1_derive/src/lib.rs
tests/derive_test.rs

Used in cases of defined by optional

Support defined by with no field

---

src/base128.rs
src/object_identifier.rs
src/parser.rs

Fixed handling of large values in base128

---

src/writer.rs
tests/roundtrip_tests.rs

Added more tests

---

README.md
fuzz/fuzz_targets/fuzz_asn1_parse.rs
src/lib.rs
src/parser.rs
src/types.rs
src/writer.rs

Rename GeneralizedTime to X509GeneralizedTime

---

Cargo.toml

I was on the fence about whether to include cryptography.

added categories to cargo.tom

---

asn1_derive/src/lib.rs

Also handle a few errors.
claude-code developed almost all of this

Refactor proc-macros to give us the theoretical ability to handle errors
