- examples/no_std.rs
- fuzz/fuzz_targets/fuzz_asn1_parse.rs
- src/parser.rs
- src/types.rs
The one requirement is that they be From<ParseError>.
> Allow callbacks to return different error types

- examples/no_std.rs
- src/parser.rs
1) There was a test that only worked on 64-bit platforms
2) the `no_std` example failed to acount for the fact that `char` is signed vs. unsigned on different platforms
> fixes #132 -- fixed building and tests on non-x86 platforms:

- Cargo.toml
- asn1_derive/Cargo.toml
To be released after https://github.com/pyca/cryptography/pull/6059 is reviewed and determined to be ready (modulo rust-asn1 release)
> Bump to 0.5.0

- src/bit_string.rs
Open question: do we want to error when asking for bits > length of bitstring or for bits that are inside the padding bit horizon? Right now it just returns false for both.
> add bitstring has_bit_set

- src/parser.rs
- src/types.rs
Also returns the correct error result if you have a truncated TLV with a tag that doesn't match any of hte CHOICE variants.
> Simplify the CHOICE implementation

- src/parser.rs
- src/tag.rs
- src/writer.rs
This is in preperation for supporting long-form tags
> Refactor tag to store passed bits, rather than just a u8.

- src/bit_string.rs
- src/parser.rs
- src/types.rs
Finishes coverage on `bit_string.rs`. Refs #274
> Make OwnedBitString parseable, in addition to writable

- Cargo.toml
because of a RUSTSEC fix (though one that doesn't impact our usage)
> specify chrono 0.4.20 as our minimum

- fuzz/fuzz_targets/fuzz_asn1_parse.rs
- src/parser.rs
- src/types.rs
And fix a case where GeneralizedTime would parse leap seconds
> Improve fuzzing to check for round-tripping

- src/parser.rs
- src/types.rs
this gives us greater confidence that we're precisely matching what DER allows. we've had several bugs due to chrono being more permissive than we realized (e.g. negative years, leapseconds)
> fixes #310 -- write our own datetime parser

- src/parser.rs
This means we keep a shorter 'backtrace' for which element failed to parse. I think 4 is probably sufficient? The other solution is to put the `parse_location` inside of a `Box`, but that means allocating, which we've avoided thus far for parsing.
> Address a new clippy error by shrinking ParseError

- fuzz/fuzz_targets/fuzz_asn1_parse.rs
- src/types.rs
- Include a raw Tlv parse (gets coverage of large tags)
- Use public accessors rather than internal data
> Several improvements from fuzzing:

- Cargo.toml
- asn1_derive/Cargo.toml
- src/base128.rs
- src/parser.rs
> Properly reject base128 integers with leading 0x80

- .github/workflows/ci.yml
- src/bit_string.rs
- src/object_identifier.rs
- src/parser.rs
- src/types.rs
- src/writer.rs
note that the tests cannot actually be _run_ under `#![no_std]` because the test runner doesn't support it, but now they at least type check
fixes #336
> ensure tests compile with `--no-default-features`

- src/writer.rs
> Impl std::error::Error for WriteError

- src/types.rs
This is needed to unlock `Hash` and `Eq` derives in `cryptography-x509`.
> types: add blanket `Eq`s for `SequenceOf` and `SetOf`

- Cargo.toml
- asn1_derive/Cargo.toml
VS Code "helpfully" did some auto-formatting of `workspace.members` as well, can pick that out if you'd prefer.
> bump version to 0.15.3

- src/types.rs
This makes `DateTime` derive `PartialOrd`, so that I can do validity window checks with it.
> types: `asn1::DateTime: PartialOrd`

- src/object_identifier.rs
> object_identifier: typo

- src/types.rs
Just a convenience API; xref https://github.com/pyca/cryptography/pull/8873.
> types: add `BigInt::is_negative` API

- src/base128.rs
I learned this trick from [AOSP source](https://android.googlesource.com/platform/art/+/ba257bc/runtime/leb128.h#101) (Apache 2.0). No practical performance differences on modern CPUs but it makes the encoding loop a bit tighter.
> Make base128_length branchless

- src/parser.rs
Calling `read_u8` repeatedly leads to multiple length checks, instead of a single one.
> When reading length bytes, read them all at once

- asn1_derive/src/lib.rs
Previously we special cased lifetimes, but these impls should work fine with other types of generics.
> Make handling of generics more general

- asn1_derive/src/lib.rs
- tests/derive_test.rs
This allows the implementation of Read and Write to be present based on whether the generic implements that trait. This is how Rust's standard derives all work.
> Add implied bounds when deriving

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- asn1_derive/Cargo.toml
- clippy.toml
- src/lib.rs
- src/parser.rs
- src/types.rs
~~WIP; I need to try this against `cryptography-x509` and see how much additional explicit typing is needed.~~
Adds length limits to `SequenceOf` via const generics + defaults. I can also do `SetOf` in a follow-up.
> types: add const generics for SequenceOf length limits

- Cargo.toml
- README.md
- asn1_derive/Cargo.toml
Bumps various versions to `0.17.0`.
> rust-asn1: bump to 0.17.0

- Cargo.toml
- README.md
- asn1_derive/Cargo.toml
Bump version to 0.18.0 as requested [here](https://github.com/pyca/cryptography/pull/11820#issuecomment-2431728920).
> Bump version to 0.18.0

- src/types.rs
It's fine to parametrize a SequenceOf with something that isn't an Asn1 type, because for SequenceOf to be an Asn1 type, T must implement the trait. In practice this is useful with certain GAT patterns.
> Remove type-bounds that aren't needed.

- Cargo.toml
- README.md
- src/lib.rs
- src/parser.rs
- src/types.rs
- src/writer.rs
Fixes https://github.com/alex/rust-asn1/issues/491
/cc @woodruffw
> Add GeneralizedTime

- asn1_derive/src/lib.rs
This prevents weird type inference errors
> Added a type annotation

- asn1_derive/src/lib.rs
- src/types.rs
- tests/derive_test.rs
See https://smallcultfollowing.com/babysteps/blog/2022/04/12/implied-bounds-and-perfect-derive/ and the test case for more details.
> Use 'perfect derives'

- README.md
- src/parser.rs
When using the API in dynamic contexts (similarly to https://github.com/alex/rust-asn1/issues/531), some field types can be difficult to read when the type information is not known at compile time.
For example, [`Choice`](https://docs.rs/asn1/latest/asn1/enum.Choice1.html) parsing requires the choice types to be known at compile time. By making `Parser::peek_tag` public, a user can check if the upcoming tag matches any of the expected Choice types, and call the appropriate method to parse it.
cc @woodruffw
> Make `Parser::peek_tag` public

- README.md
- src/parser.rs
As discussed in https://github.com/alex/rust-asn1/issues/531, this PR reintroduces the `Parser::read_implicit_element` and `Parser::read_explicit_element` methods that were removed in https://github.com/alex/rust-asn1/commit/74ff00f3a65e9ad52ef78f1f755cbf6f03226242
cc @woodruffw @alex
> Re-add `Parser::read_{explicit,implicit}_element` methods

- src/types.rs
I think these should be `Asn1Read` and `Asn1Write`, as used in [here](https://github.com/pyca/cryptography/blob/be6c53dd03172dde6af2de775a9d8e65e6b60fb0/src/rust/cryptography-x509/src/name.rs#L52-L83)
cc @woodruffw
> Fix CHOICE docs to match current API

- README.md
- asn1_derive/src/lib.rs
- src/tag.rs
- src/types.rs
- src/writer.rs
shows a 60% improvement at `serialize_basic_struct/size_10000` (there's also a smaller performance improvement for the parse benchmarks, but there's no valid reason for those to occur, so I'm ignoring)
> fixes #340 -- allow types to provide their length to reduce allocations

- src/types.rs
- Add data_length to BitString<'_>
- Add data_length to OwnedBitString
- Add data_length to BigUint<'_>
- Add data_length to OwnedBigUint
- Add data_length to BigInt<'_>
- Add data_length to OwnedBigInt
- Add data_length to Enumerated
> Batch 1: Add data_length implementations

- src/types.rs
- Add data_length to Sequence<'_> (returns data slice length)
- Add data_length to SequenceOfWriter<'_, T, V> (sums encoded_length of all elements)
- Add data_length to SetOfWriter<'_, T, V> (sums encoded_length of all elements)
> Batch 4: Add data_length implementations

- src/types.rs
- Add data_length to Implicit<T, {TAG}>
- Add data_length to &T (reference to SimpleAsn1Writable type)
- Add data_length to Box<T> (boxed SimpleAsn1Writable type)
> Batch 2: Add data_length implementations

- README.md
- src/writer.rs
This PR reintroduces the `Writer::write_implicit_element` and `Writer::write_explicit_element` methods that were removed in https://github.com/alex/rust-asn1/pull/500/files
The only change is that `write_tlv()` is now called passing the precomputed length of the value to be written (using `Asn1Writable::encoded_length` for `EXPLICIT` values and `SimpleAsn1Writable::data_length` for `IMPLICIT` values).
> Re-add `Writer::write_{explicit,implicit}_element` methods
